import type { GridDetail } from "./types";

const columns = [
  ["repo_url", "Repository", "input", 250],
  ["canonical_name", "Canonical name", "transform", 175],
  ["github_snapshot", "GitHub snapshot", "github", 150],
  ["stars", "Stars", "transform", 105],
  ["primary_language", "Language", "transform", 125],
  ["license", "License", "transform", 105],
  ["last_push", "Last push", "transform", 135],
  ["latest_release", "Latest release", "transform", 145],
  ["activity", "Issue / PR activity", "transform", 165],
  ["health_score", "Health", "transform", 100],
  ["readme_summary", "Sourced summary", "llm", 290],
  ["recommendation", "Recommendation", "llm", 260],
] as const;

const data = [
  [
    "https://github.com/openai/openai-python",
    "openai/openai-python",
    { repository: { stargazers_count: 31842 }, languages: { Python: 100 } },
    "31,842",
    "Python",
    "Apache-2.0",
    "2h ago",
    "2026-08-01",
    { recent_issues: 11, recent_pull_requests: 19 },
    94,
    "Official Python client with typed request models, streaming helpers, and broad API coverage.",
    "Adopt for first-party OpenAI Python integrations.",
  ],
  [
    "https://github.com/fastapi/fastapi",
    "fastapi/fastapi",
    { repository: { stargazers_count: 91124 }, languages: { Python: 100 } },
    "91,124",
    "Python",
    "MIT",
    "5h ago",
    "2026-07-28",
    { recent_issues: 14, recent_pull_requests: 16 },
    97,
    "High-performance API framework built around Python type hints and automatic OpenAPI documentation.",
    "Adopt for typed Python APIs when ASGI fits the stack.",
  ],
  [
    "https://github.com/OpenHands/OpenHands",
    "OpenHands/OpenHands",
    { repository: { stargazers_count: 74613 }, languages: { Python: 80, TypeScript: 20 } },
    "74,613",
    "Python",
    "MIT",
    "1h ago",
    "2026-08-03",
    { recent_issues: 18, recent_pull_requests: 12 },
    89,
    "A software development agent platform with local and cloud runtimes for code-changing tasks.",
    "Watch if you need an extensible coding-agent platform.",
  ],
];

export const sampleGrid: GridDetail = {
  id: "sample-grid",
  name: "GitHub Repository Radar",
  description: "Compare repository momentum, maintenance, and product signals.",
  schema_version: 1,
  canvas_layout: {},
  columns: columns.map(([key, label, kind, width], index) => ({
    id: `sample-column-${index}`,
    key,
    label,
    kind,
    width,
    position: index,
    depends_on: index === 0 ? [] : [columns[Math.max(0, index - 1)][0]],
    config: {},
    prompt: null,
    output_schema: {},
  })),
  rows: data.map((row, rowIndex) => ({
    id: `sample-row-${rowIndex}`,
    position: rowIndex,
    cells: row.map((value, cellIndex) => ({
      id: `sample-cell-${rowIndex}-${cellIndex}`,
      column_id: `sample-column-${cellIndex}`,
      status: "succeeded",
      value,
      provenance: {
        id: `sample-provenance-${rowIndex}-${cellIndex}`,
        connector: cellIndex >= 10 ? "llm:anthropic" : cellIndex === 0 ? "input" : "github",
        source_urls: [String(row[0])],
        artifact_hash: `sha256:${"a7c3d9e4".repeat(8)}`,
        input_hash: `sha256:${"42f1b8d0".repeat(8)}`,
        model: cellIndex >= 10 ? "claude-sonnet" : null,
        prompt: cellIndex >= 10 ? "Use only the supplied repository evidence." : null,
        input_tokens: cellIndex >= 10 ? 1348 : 0,
        output_tokens: cellIndex >= 10 ? 61 : 0,
        cost_usd: cellIndex >= 10 ? 0.0062 : 0,
        duration_ms: cellIndex >= 10 ? 2183 : 342,
        cache_hit: cellIndex > 0 && cellIndex < 10,
        created_at: new Date().toISOString(),
        metadata: { demo: true },
      },
    })),
  })),
};
