"""initial sourcedgrid schema

Revision ID: 35a3bdad004e
Revises:
Create Date: 2026-08-11 18:12:25.443511
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "35a3bdad004e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=180), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "encrypted_secrets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encrypted_secrets_name"), "encrypted_secrets", ["name"], unique=True)
    op.create_table(
        "grids",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("template_slug", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("document_yaml", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_templates_slug"), "templates", ["slug"], unique=True)
    op.create_table(
        "column_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grid_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=180), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grid_id"], ["grids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grid_id", "key", name="uq_columns_grid_key"),
    )
    op.create_index(op.f("ix_column_definitions_grid_id"), "column_definitions", ["grid_id"], unique=False)
    op.create_table(
        "grid_rows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grid_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grid_id"], ["grids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grid_id", "position", name="uq_rows_grid_position"),
    )
    op.create_index(op.f("ix_grid_rows_grid_id"), "grid_rows", ["grid_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("grid_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("budget_usd", sa.Float(), nullable=False),
        sa.Column("spent_usd", sa.Float(), nullable=False),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column("failed_tasks", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grid_id"], ["grids.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_grid_id"), "runs", ["grid_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "cells",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("column_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cache_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["column_id"], ["column_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["row_id"], ["grid_rows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("row_id", "column_id", name="uq_cells_row_column"),
    )
    op.create_index(op.f("ix_cells_cache_key"), "cells", ["cache_key"], unique=False)
    op.create_index(op.f("ix_cells_column_id"), "cells", ["column_id"], unique=False)
    op.create_index(op.f("ix_cells_row_id"), "cells", ["row_id"], unique=False)
    op.create_index(op.f("ix_cells_status"), "cells", ["status"], unique=False)
    op.create_table(
        "run_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("column_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=120), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cache_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["column_id"], ["column_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["row_id"], ["grid_rows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "row_id", "column_id", name="uq_tasks_run_row_column"),
    )
    op.create_index(
        "idx_tasks_claim", "run_tasks", ["status", "available_at", "lease_expires_at"], unique=False
    )
    op.create_index(op.f("ix_run_tasks_column_id"), "run_tasks", ["column_id"], unique=False)
    op.create_index(op.f("ix_run_tasks_row_id"), "run_tasks", ["row_id"], unique=False)
    op.create_index(op.f("ix_run_tasks_run_id"), "run_tasks", ["run_id"], unique=False)
    op.create_table(
        "provenance",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cell_id", sa.String(length=36), nullable=False),
        sa.Column("connector", sa.String(length=80), nullable=False),
        sa.Column("source_urls", sa.JSON(), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=180), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_hash"],
            ["artifacts.hash"],
        ),
        sa.ForeignKeyConstraint(["cell_id"], ["cells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cell_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provenance")
    op.drop_index(op.f("ix_run_tasks_run_id"), table_name="run_tasks")
    op.drop_index(op.f("ix_run_tasks_row_id"), table_name="run_tasks")
    op.drop_index(op.f("ix_run_tasks_column_id"), table_name="run_tasks")
    op.drop_index("idx_tasks_claim", table_name="run_tasks")
    op.drop_table("run_tasks")
    op.drop_index(op.f("ix_cells_status"), table_name="cells")
    op.drop_index(op.f("ix_cells_row_id"), table_name="cells")
    op.drop_index(op.f("ix_cells_column_id"), table_name="cells")
    op.drop_index(op.f("ix_cells_cache_key"), table_name="cells")
    op.drop_table("cells")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_grid_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_grid_rows_grid_id"), table_name="grid_rows")
    op.drop_table("grid_rows")
    op.drop_index(op.f("ix_column_definitions_grid_id"), table_name="column_definitions")
    op.drop_table("column_definitions")
    op.drop_index(op.f("ix_templates_slug"), table_name="templates")
    op.drop_table("templates")
    op.drop_table("grids")
    op.drop_index(op.f("ix_encrypted_secrets_name"), table_name="encrypted_secrets")
    op.drop_table("encrypted_secrets")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
